batch:
  queue-dir: C:/queue
  repo-dir: C:/grassKeeper

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-all.sql